### ISSUE TITLE
[SharkAttack_Project] Alejandro Sánchez

### ISSUE THREAD

**Issue by as-Solo** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#10]
https://github.com/as-Solo/SharkAttack_Project

**Comment by breogann** [comment]
Hola Alejandro! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - No tienes ningún archivo tipo ipynb_chckpoints que se te haya colado. Entiendo que o los has borrado o los has evitado a la hora de hacer el git add. En cualquier caso perfecto. Sí que te diría que aprovechases para utilizar el gitignore, que así te aseguras.

            Lo que sí que has subido es ¿el csv original? (sí, no? no se me carga).  Recuerda que los autores piden que no se suba. Para quitarlo de github, puedes usar:

            ```
            git rm --cached .ipynb_checkpoints
            ```

            Luego guardarlo en el .gitignore y volver a repetir el proceso de add, commit y push.

    - Para la organización de carpetas y la distribución de los jupyters, está perfecto. Igual con la modularización del archivo de funciones.
    - Te dejo esto, por si le quieres echar un ojo: pipreqs [https://pypi.org/project/pipreqs/](https://pypi.org/project/pipreqs/). Para este proyecto no lo pedimos, para los siguientes probablemente sí. Es en la línea de lo que hablábamos ayer de los entornos (te genera el requirements.txt automáticamente).
    - También puedes aprovechar para guardar las gráficas que has ploteado y guardarlas en la carpeta de data.
- El **[README.md](http://readme.md/) ✍🏻**: el proceso que has seguido está súper bien explicado. Si quisieras completar con cosas nuevas, puedes incluir las hipótesis, enlaces a la documentación de las librerías que nombras al principio, algún ejemplo de gráfica, etc. Como os decíamos, no hay una forma 100% correcta de hacer el readme, aquí os dejamos sugerencias por si vosotros creéis que os añade valor. Si no, has dejado igualmente explicado el proceso, y eso está perfecto.
- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py/) con nombres significativos (limpieza_texto.py) o sea que 👏, era lo que pedíamos.
- El **código 👩‍💻:**
    - Las docstrings están muy top.
    - La limpieza y el story telling:
        - Cuando te quedas con las columnas que necesitas, estás haciendo drop de las columnas que no usas. Puedes, o bien ignorar las que no utilizas, o si lo quieres tener más "limpio" puedes hacer un sub dataframe con las columnas que usas.  Además, has droppeado de una forma muy manual. Tienes línea de código muy parecidas muy repetidas: eso siempre es indicación de que puedes crear una función. Quizá puedes hacer algo sencillo que sea: hacer una lista con las columnas que utilizas y un bucle que te itere dropeando todas las columnas que no están en esa lista.
        - Has utilizado las funciones que has definido y has modificado las columnas con apply's 👏
        - Los jupyters están súper bien comentados y muy guiados.
        - En esta función:

            ```python
            for key, value in especies_dict.items():
                    if key in respuesta:
                        respuesta = value
                        return respuesta
            ```

            puedes hacer directamente return value y quitarte esa línea:

            ```python
            for key, value in especies_dict.items():
                    if key in respuesta:
                        return value
            ```

            Que sé que lo sabes perfectamente, pero a mí me parece más cómodo de leer; igual a ti te parece más claro como lo tienes.

            El resto del código lo veo genial, la verdad. (Veo que has evitado regex a toda costa 🥲; no te culpo. Pero se le coge cariño, te lo prometo).

        - Para la visualización:
            - Has hecho countplots "sencillos", muy explícitos, enseñando lo que tienes que enseñar. No te has metido en plots fantasía porque no te ha hecho falta.

    Como conlusiones, te diré:

    - Has modularizado el código y lo has documentado bien
    - Tienes unas hipótesis claras y has hecho una limpieza coherente (quitando los dropss)
    - Tienes una visualización ajustada y explícita.
    - Nos comentabas que cambiaste de hipótesis en algún momento del fin de semana. Aun así el proyecto te ha quedado bien. Con esto quiero decir: tienes capacidad para enfangarte mucho más y hacer más limpieza, explorar otras librerías, etc; y te animo a ello!
    - Yo también atacaría más los domingos sabiendo que el día siguiente es lunes.

    Buen trabajo Alejandro 💪

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)

**Comment by breogann** [comment]
Ah! Y genial también el uso de try/except!
