### ISSUE TITLE
[w2-pandas-project] Fran Leston

### ISSUE THREAD

**Issue by FranLeston** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#11]
[Shark Analysis](https://github.com/FranLeston/shark_attack_data_analysis)

**Comment by AnaAGG** [comment]
# Proyecto sharks 🦈🦈

Hola Fran!!! Por aquí estoy con la revisión de tu proyecto de tiburones. 

## Readme

Muy buen trabajo con el Readme Fran, hiciste un trabajo que invita a seguir leyendo, fácil de seguir y resumiendo muy bien todo el trabajo realizado. Me gusta que hayas puesto algunas gráficas en el readme (sobre esto no hay convención, es una decisión más personal) y con una gráficas espectaculares!

Como detalle, y solo por ponerme un poco tiquismiquis, cuando pones las librerías que usaste sería perfecto que pusieras el link a la documentación oficial de cada una de ellas, además, no hace falta que pongas `pip install pandas` o `import pandas as pd`. Poniendo solo pandas sería suficiente, pero vamos que esta de 10!. 

## Estructura del repositorio

- Estupendo! Has metido todo lo necesario en el gitignore y no se te ha quedado por ahí ningún fichero raro.
En cuanto a los jupyter, los puedes meter en otra carpeta a la que puedes llamar 'Notebooks' o 'Analysis'. El nombre vuelve a ser personal, pero si los metes en otra carpeta sería perfecto!

- En las funciones me faltó el docstring (que es lo que hace la función, que es lo que recibe, que tipo tienen los parámetros que recibe la función y lo que nos devuelve). 

- El archivo `visualización.py` si no usaste ninguna función para la visualización lo mejor es eliminarlo y no dejar un archivo vacío. 

- Otro detallin por ponerse tiquismiquis. Tienes todo el proyecto hecho en inglés lo cual esta perfecto. Intenta que los nombres de los ficheros también vayan en inglés.

- La función  `clean_age` se podría "ordenar" un poco más y meter el `if` en el try/except
    ```python
    def clean_age(age):
        try:
            if (int(age) > 0 and int(age) <= 100):
                return int(age)
        except:
            return np.nan
    ```

## Síntaxis de código

- En el fichero de `preliminarynotes` cuando aplicas la función `get_moon` te sale un output larguisimo. Esto puede distraer la atención del lector o que con el scroll te puedas saltar algún paso. Te recomiendo que intentes limitar el output en este tipo de situaciones! 

- Cuando reasignas el nombre de algunas columnas para quitar los espacios, como lo haces creando un diccionario esta perfecto. Si bien, para este caso se puede hacer, imagina que tienes un dataframe con 20 columnas a las que a todas les tienes que quitar un espacio. Usar un diccionario puede ser poco eficiente. Te dejo por aquí unas lineas de código por si te aportan valor con otra posible opción. 

    ```python
    # Como lo hiciste con el diccionario 🔝
    df_cleaned.rename(columns={'Species ': 'Species', 'Sex ': 'Sex', 'Fatal (Y/N)': 'Fatal' }, inplace=True)


    # Otra opción
    df_cleaned = df_cleaned.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings

    df_cleaned = df_cleaned.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja

    ```
- En general lo hiciste pero es importantísimo poner lo que son los ejes de las gráficas para facilitar la interpretación de la gráfica por parte del lector. 

## ToDo
Te pongo por aquí un par de detallitos que podrías cambiar para darle más valor a tu trabajo:

- Explicación con markdown en el jupyter de visualización
- Me ha faltado un poco de *story telling* en el jupyter de visualización, vender un poco más tu historia metiendo "fantasía" a modo de explicación de los gráficos.


En computo general muy muy buen trabajo Fran!!! Enhorabuena!

PD: me han flipado tus gráficas 🤩

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)

**Comment by FranLeston** [comment]
Gracias Ana!!!

Fran
________________________________
