### ISSUE TITLE
[Shark-Attack] Javier Cabrera

### ISSUE THREAD

**Issue by Javi-Python** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#12]
https://github.com/javielpapi/Projecto-Shark-Attack-Data-Cleaning

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola hola Javi!! Vamos a por la corrección del proyecto de tiburones!!! Menudo turrazo te he metido, pero no te asustes! El proyecto esta super bien, con un hilo claro y con un código muy bien estructurado!!!!

## Readme

- El readme, cortito pero al grano! Muy bien explicado.

- Cuando describes en que consiste el proyecto, suuper bien!!! Queda muy claro cual va a ser el *workflow* de repo. 

- Como detalles, me faltan un par de cositas en el readme:
    - Dado que no se puede dejar la base de datos que has usado para hacer la limpieza en el repo, hubiera estado muy bien que añadieras un link a la página donde se pueden descargar los datos.

    - Poner las librerías que has usado para este proyecto, y si ya pones los links que lleven a la documentación oficial de cada página sería la leche. 

    - Una pequeña descripción(en una o dos líneas) explicando de que va la base de datos. 


## Estructura del repositorio

Vamos a por la estructura del repo. Genial! Todas las funciones con su docstring!!! 🔝🔝🔝. En general está bastante bien organizado y se sigue bien. Pero te dejo por aquí unos tips para las próximas: 

- En el readme presentas 2 hipótesis, pero ya en el primer jupyter hablas de tres. Lo ideal sería que unificaras su número y que fueran consistentes a lo largo del proyecto. 

- Tienes tus carpetas de funciones, de datos y de imágenes. Aún así, tienes alguna figura por ahí suelta fuera de la carpeta como White Sharks Attack Activities, White Shark Attack Age Distribution, Species & Fatality, Activity & Sex

- El `.gitignore` lo tienes creado pero vacío 🤷‍♀️. En ese fichero deberían ir los archivos como `.DS_Store`, `__pycache__` o el csv de los datos que no debería poner en el repo.

- El archivo funciones, genial, pero no lo llames funciones! Dale un nombre más descriptivo, por ejemplo "cleaning". 

- Tienes muchos jupyter, lo cual está perfecto!! Enfrentando el problema en pequeños trocitos. Aquí por ponerme un poco tiquismiquis: 

    - Puedes meterlos también en una carpeta y que quede todo perfectitamente ordenado

    - De la misma forma que lo tienes en el readme con números que indican el orden, puedes ponerle números también a los jupyter y ya quedaría perfectooo


## Sintaxis de código

- El análisis preliminar que haces esta perfecto!! Investigas que columnas hay, de que tipo es cada columna, cuantos nulos hay en el dataset

- La función `sumnull` genial que la hayas hecho, peerooo la clave de las funciones es crear nuestras propias funciones que estructuren código de forma más legible y reutilizarlas en partes que se repiten mucho. Crear una función para un `isnull`q que vamos a hacer en una línea no es lo ideal. Pero esta bien que te hayas arrancado con las funciones, este proyecto no es el mejor para volverse con las funciones. 

- Cuando reasignas el nombre de algunas columnas para quitar los espacios, como lo haces esta perfecto. Si bien, para este caso se puede hacer, imagina que tienes un dataframe con 20 columnas a las que a todas les tienes que quitar un espacio. Usar un diccionario puede ser poco eficiente. Te dejo por aquí unas líneas de código por si te aportan valor con otra posible opción. 

    ```python
    df_cleaned = df_cleaned.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings

    df_cleaned = df_cleaned.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja

    ```

- ¿Por qué haces esto? `pd.to_numeric(sharks_age['Age_Regex'])`. Tu columna `Age_Regex` ya es un integer. Lo conviertes a un float lo cual no tiene mucho sentido para una variable como edad. 

- Venga vamos a por la columna de `Species`. En primer lugar genial que te lanzaras con esa columna! Perfecto como lo sacaste. Muy eficiente sacar aquellas especies que más se repiten en vez de todas (esa era clave). Como tip te comento que se puede atomizar un poco ese código usando una función y un diccionario. Te dejo por aquí unas líneas de código, si te quedan dudas dime y lo vemos: 
    ```python
    def species (col):
        diccionario = {
        "white" : re.search(r".*[Ww](hite|HITE).*", str(col)),
        "tiger" : re.search(r'.*[Tt].*', str(col)), 
        "grey" : re.search(r'.*[Gg](rey|ray).*', str(col)),
        "lemon" : re.search(r'.*[Ll].*', str(col)),
        "bull" : re.search(r'.*[Bb](ull).*', str(col))

        } 
        for k,v in diccionario.items():
            if v == True:
                return k
            else:
                return col
    ```

- Cuando cargas el csv con los datos limpios por ponerme tiquismiquis hay una forma para que no te apareca la columna XXX evitando así tener que eliminarla:
    ```python
    df = pd.read_csv(df.to_csv, index=False)
    ```

- Muy bien como has decidido seleccionar aquellas actividades que más representadas están en el dataset. 


## ToDo

- Unifica las hipótesis planteadas a lo largo del repo.

- ❗ Cuidado con los drops ❗ Los datos son muy valiosos y cuesta mucho conseguirlos. Eliminar todos los datos de una fila porque en una celda a un `na` es un poquito heavy 😂. Por ejemplo, si tienes un NaN en una celda de `Species`, eliminar todos los valores que se han recogido para `Activity, Age o Sex` te puede estar haciendo perder mucha información!

- Atomizar algunas estructuras de código como por ejemplo en el limpiado de la columna `Species`. Lo mismo para cuando creas las figuras, date cuenta que tienes estructuras de código que se repiten bastante. 

- Algo ha pasado con las imágenes en el tercer jupyter, no se ven 😢. Pero este jupyter esta muy muy bien! Un buen resumen y *Story telling*!!! 🚀🚀🚀🚀

> LA CONLUSIÓN... 🔝🔝 Don't Be A Surfer If You Don't Wanna Get Eate 🔝🔝

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
