### ISSUE TITLE
[w2-pandas-proyect]Carmen Rdriguez

### ISSUE THREAD

**Issue by Carmen-r** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#13]
https://github.com/Carmen-r/w2-pandas-project.git

Me hubiese gustado haber hecho más hipótesis o haberlas enrevesado un poco más pero ha habido funciones que las he descubierto tarde y he perdido muchas horas investigando sobre la limpieza de datos.!!! Para el próximo más y mejor!

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola Carmen!!! Ya estoy por aquí con las correcciones del proyecto de tiburones. 

## Readme

Vamos con el readme, en general la estructura esta muy bien aunque me han faltado unos detallitos: 
-  Genial que hayas incluido las librerías que usaste en el proyecto, por ponerme tiquismiquis quedaría perfecto si añades el link a las páginas de la documentación oficial. 

- Podrías incluir una pequeña descripción del dataset, que es lo que contiene o que información nos da, así como el link al la página donde se puede descargar.  

- Explicas muy bien el análisis preliminar pero me faltó algún detalle más sobre la limpieza "gorda". 

- ‼ Tenemos que mirar que esta pasando con esas imágenes que no se te cargan y no se ven, es una pena 😢‼ Dime cuando quieras y lo vemos, te será super útil para el futuro. 

## Estructura del repositorio

En general esta perfecta! Te dejo por aquí algunos comentarios son algunas cositas que se podrían mejorar sobre la estructura del repo:  

- Tienes una carpeta que se llama `misdatasetslimpio.csv` supongo que se te habrá pasado, pero intenta no crear carpetas que tengas extensiones puede llevar a una confusión. 

- Tienes todos los jupyters con números, me encanta! Ya le estas indicando a la persona que vaya a ver tu repo cual será el orden que tenga que seguir. 🔝. Sin embargo, tienes un jupyter que no tiene número `limpieza.ipynb`. Si es un jupyter que no te interesaba mostrar recuerda que lo puedes meter en el `.gitignore`

- El `.gitignore` esta perfecto! No se te escapo ningún fichero raro ni que no se debiera ver!

- El archivo `visualización.py` si no usaste ninguna función para la visualización lo mejor es eliminarlo y no dejar un archivo vacío. 

- En cuanto a los jupyter, solo por ponerme un poco tiquismiquis, los puedes meter en otra carpeta a la que puedes llamar 'Notebooks' o 'Analysis'. El nombre es un tema un poco más personal, pero si los metes en otra carpeta sería perfecto!

- Tienes todo el proyecto en inglés, intenta poner los nombres de los jupyter también en inglés. 

- Suuuupper bien que hayas comentado cada cosa que fuiste haciendo y además usando celdas de markdown!!!! 

- Creas tres datasets independientes para cada una de las hipótesis. Esta bien, pero lo ideal es que te crearas un único dataset completamente limpio con que trabajaras para testar todas tus hipótesis.

Parece mucho pero que no baje el ánimo que son todo pequeños detalles!!! Hiciste buen trabajo en el readme

## Sintaxis de código
Vamos con algunas cosinas del código 💪🚀:

- En el primer jupyter, decides eliminar columnas que tengan más de 20,000 datos nulos, lo cual esta bien y era una decisión personal. Pero fíjate que eliminaste columnas que *a priori* pueden parecer importantes como especies o edad. Una de las características de este dataset es que tenía muchas filas vacías. Otra opción era eliminar filas primero y luego columnas. 

- En el segundo jupyter, cuando te creas la nueva columna `Hemispheres` super bien. A modo de detalle, si te fijas tienes una estructura que se repite un poco. Cuando te encuentres en estos casos lo mejor es atomizar el código. En este caso te podrías haber creado una función. Te dejo por aquí unas líneas de código por si te aporta valor: 

    ```python
    def get_hemispheres (col):
        col = col.lower()
        hn = ["usa", "italy", "mexico", "bahamas"]
        hs = ["brazil", "south africa", "australia", "new zeland", "papua new guinea", "new guinea"]
        if col in hn:
            return Hemisphere-N
        elif col in hs:
            return Hemisphere-S
        else:
            return col
    ```
    Después hace un apply sobre la columna.

- Las funciones recuerda dejarlas siempre en el .py y en el jupyter solo importarlas y llamarlas. 

- Las funciones que creaste perfectas, cortitas y con un objetivo claro que se pueden usar para otras cosas, esa es la clave! 

- Los `import` fuera de las funciones. Muy probablemente lo hicieras así porque te estaba dando error. Si es así coméntamelo y lo vemos!
 

## ToDo

- Me ha faltado un poco de *story telling* en el jupyter de visualizacion, vender un poco más tu historia metiendo "fantasía" a modo de explicación de los gráficos.

- Darle una vuelta al Readme, hay que mirar esas imágenes que no se ven

Buen trabajo Carmen! En este lab te has enfrentado a un dataset que estaba sucísimo y lo hiciste genial! 

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
