### ISSUE TITLE
[Shark attack] Edu Martinez

### ISSUE THREAD

**Issue by EduMartinezGarrido** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#14]
https://github.com/EduMartinezGarrido/Shark-attacks.git

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola hola Eduuuu!! Vamos a por la corrección del proyecto de tiburones!!! 

## Readme

- Una cosa que me chirrió un poco, en el readme tienes texto en inglés y en español. Intenta unificar un poco el idioma. Lo ideal es que lo hagas todo en inglés si te sientes cómodo. 

- Sobre las librerias, no hace falta que pongas `import pandas as pd` con que pongas `pandas` es suficiente. Sería perfecto que pusieras los links que te llevarán a las páginas de la documentación oficial de las librerías. 

## Estructura del repositorio

- EL archivo `.gitignore`, genial has metido el `.csv` de los datos, el  `__pycache__` peeero... se te ha colado el `.DS_Store` y si te metes en la carpeta de data sigo viendo los archivos de datos. Esto será porque lo tendrías duplicados los ficheros. Hay que mirarlo y quitar estos ficheros vale??

- No llames al archivo .py de las funciones `funciones`. El nombre de estos ficheros tiene que ser descriptivo, por ejemplo `cleaning_functions.py`

- Recuerda los docstring de las funciones, son importantes para los que verán tu código, para que entiendan que hace tu función y que parámetros recibe. 


## Síntaxis de código

- Muy bien que hayas trabajado con los porcentajes relativos para hacer las gráficas Edu!

- Cuando reasignas el nombre de algunas columnas para quitar los espacios, como lo haces creando un diccionario esta perfecto. Si bien, para este caso se puede hacer, imagina que tienes un dataframe con 20 columnas a las que a todas les tienes que quitar un espacio. Usar un diccionario puede ser poco eficiente. Te dejo por aquí unas líneas de código por si te aportan valor con otra posible opción. 

    ```python
    # Como lo hiciste con el diccionario 🔝
    df_cleaned.rename(columns={'Species ': 'Species', 'Sex ': 'Sex', 'Fatal (Y/N)': 'Fatal' }, inplace=True)


    # Otra opción
    df_cleaned = df_cleaned.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings

    df_cleaned = df_cleaned.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja

    ```
- Cuando rellenas los na en el dataframe usando `fillna` esta bien, pero date cuenta que has repetido 5 veces la misma línea de código lo que puede resultar en algo poco eficiente. En estas situaciones hay que intentar atomizar el código. ¿Cómo lo podrías hacer?
    -  Puedes crear una función 
    -  En este caso lo que más fácil hubiera sido es aplicar el método `fillna` en todo el dataframe

        ```python
        df = df.fillna("POR LO QUE LO QUIERAS REEMPLAZAR") # así te lo hará en todo el dataset. Independientemente de la columna
        ```

- En la limpieza de la columna `Activity` tienes definidas dos funciones y dos variables (una con un patrón de regex y otra con los stri
ng que vas a reemplazar), perooo donde aplicas esas funciones?? 🤷‍♀️ 

- Intenta no llamar a variables con el nombre de métodos propios de python. Como el replace que tienes en la limpieza de `Activity`

    ```python
    replace = ["swimming","surfing","paddling","fishing","spearfishing","wading","scubadiving","snorkeling","walking","free_diving","body_boarding"]
    ```

- Los ejes en las gráficas son esenciales, que la persona que este vea tus resultados no tenga que adivinar que representa cada eje. 

- Recuerda, todas las funciones al .py y las importas en jupyter notebook

- En la limpieza de la columna `sex` creas una función para sacar tres categorías (Female, male y unknown). La función esta bien y la sintáxis perfect. Peeero... cuando haces el primer `unique` para testar cuantos valores únicos hay ya te salen esas tres categorías. Entonces para que la usas?


## ToDo

- Atomizar el código por ejemplo en la columna activity intenta sacar un regex más general y que no tengas que escribir un regex para cada una de las actividades. 

- Esas funciones para limpiar la columna `Activity` que luego no vuelves a usar en ningún momento. 

- El readme, unifícalo por favor!

- Los ejes en las figuras, que de un vistazo el lector pueda entender lo que estas representando en la figura. 

- Me falto un poco de *Story telling* en la parte final del proyecto. Algo de fantasía y de contar una historia que una todas tus hipótesis. 

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
