### ISSUE TITLE
[Shark-Attack] Alberto Pérez-Lescure

### ISSUE THREAD

**Issue by Albertoplm** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#15]
[Link to my repo](https://github.com/Albertoplm/Shark-Project.git)

https://github.com/Albertoplm/Shark-Project.git

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola hola Alberto!! Vamos a por la corrección del proyecto de tiburones!!! El proyecto esta super bien, con un hilo claro y con un código muy bien estructurado!!!!

## Readme

El readme genial, super sencillo de seguir y muy bien resumido todo lo que hiciste en el proyecto. Solo como detalle de dejo por aquí un comentario:

-  Muy bien que hayas puesto las librerías que has usado para este proyecto, si ya pones los links que lleven a la documentación oficial de cada página sería la leche. 


## Estructura del repositorio

En general la estructura del repo esta perfecta, solo un par de cosinas:

- Muy bien las funciones con su docstring 🚀🚀!! 

- El archivo `.gitignore` perfecto. Has metido la base de datos. Solo como detalle, se te ha pasado un archivo que debería ir también en el gitignore, el `__pycache__`. 

- Aunque hayas metido los ficheros de los datos en el .gitignore se siguen viendo los ficheros... ten cuidadin con eso. 

- En cuanto a los jupyter, solo por ponerme un poco tiquismiquis, los puedes meter en otra carpeta a la que puedes llamar 'Notebooks' o 'Analysis'. El nombre es un tema un poco más personal, pero si los metes en otra carpeta sería perfecto! 

- Si no creas ninguna función para la visualización elimina ese fichero. Puede generar un poco de confusión. ¿No hay funciones porque no las creaste o porque no las subiste al repo al final?


## Sintaxis de código
 
Vamos a por algunos comentarios sobre el código:

- Muyyy bien que uses el método `rstrip` para eliminar los espacios que hay al inicio o al final del nombre de las columnas. Otros espacios que suelen dar problemas son los que hay en el medio. Para eliminar estos espacios puedes usar el método `replace` te dejo por aquí un ejemplo por si te aporta valor: 

  ```python

    data = data.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja

    ```

- La función `isnull` genial que la hayas hecho, peerooo la clave de las funciones es crear nuestras propias funciones que estructuren código de forma más legible y reutilizarlas en partes que se repiten mucho. Crear una función para un `isnull` que vamos a hacer en una línea no es lo ideal. Pero esta bien que te hayas arrancado con las funciones, este proyecto no es el mejor para volverse con las funciones. 

- Super bien la función `coincidecia`, la has creado de tal forma que te vale para limpiar varias columnas. Peroooo no sabía yo que los tiburones tuvieran DNI!!! 😉

- ❗ Ojo con reemplazar todos los null por 0 ❗ En algunos casos puede ser útil pero por ejemplo en la columna edad hay opciones más interesantes. Por ejemplo, reemplazar con la media de edad de los datos que tenemos.  

- Venga vamos a por la columna de `Species`. En primer lugar genial que te lanzaras con esa columna! Perfecto como lo sacaste. Muy eficiente sacar aquellas especies que más se repiten en vez de todas (esa era clave). Como tip te comento que se puede atomizar un poco ese código usando una función y un diccionario. Te dejo por aquí unas líneas de código, si te quedan dudas dime y lo vemos: 
    ```python
    def species (col):
        diccionario = {
        "white" : re.search(r".*[Ww](hite|HITE).*", str(col)),
        "tiger" : re.search(r'.*[Tt].*', str(col)), 
        "grey" : re.search(r'.*[Gg](rey|ray).*', str(col)),
        "lemon" : re.search(r'.*[Ll].*', str(col)),
        "bull" : re.search(r'.*[Bb](ull).*', str(col))

        } 
        for k,v in diccionario.items():
            if v == True:
                return k
            else:
                return col
    ```
    Además así trabajas con otras formas de enfrentarte a un problema. 

- 🟠 Los import siempre fuera de las funciones 

- En las gráficas de `Gender attack rate`, `Type of injury` y `Type of shark` y `Worst time to be in the water`, ¿Qué sentido tiene que le metas el eje de la derecha? Quiero decir, tienes las barras que están representadas por el eje de la izquierda, con este eje se entiende toda la gráfica. 

## ToDo

- Me ha faltado un poco de *story telling* en el jupyter de visualización, vender un poco más tu historia metiendo "fantasía" a modo de explicación de los gráficos.

- Esas funcioncitas del dni de los tiburones...

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
