### ISSUE TITLE
[Shark-project] Antonio Pita 

### ISSUE THREAD

**Issue by Antoniopita95** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#16]
https://github.com/Antoniopita95/-w2-pandas-project-Antonio-Pita.git

**Comment by breogann** [comment]
Hola Antonio! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - ¿Has cogido una plantilla (al crear el proyecto) que no es de python?
        - Se te ha colado un archivo temporal en la carpeta de src: **pycache**. Tendrías que decirle a git que deje de trackearlo.

            ```python
            git rm --cached elarchivo
            ```

            luego añadirlo al .gitignore, hacer add y push de nuevo. 

        - Lo que tienes en los [archivos.py](http://archivos.py) son las funciones plantilla que pusimos, pero no has modularizado el código.
- El **[README.md](http://readme.md/) ✍🏻**: No tienes 🔪. Es súper importante que lo hagas. Ten en cuenta que será tu portfolio.
- El **código 👩‍💻:**
    - Si reutilizas la función de regex, cambia el nombre de las variables, que no se quede con DNI.
    - Tamnbién, las importaciones siempre están fuera de las funciones. Si no, has importado regex por cada vez que has pasado la función. Es decir, lo habrás cargado 30.000 veces (si hay 30.000 filas)
    - Para la visualización; el último gráfico no se puede interpretar: no se ven los datos y tampoco se pueden leer las etiquetas del eje X.

    El proyecto se me queda un poco cojo. Puedes hacer más limpieza y modularizar el código. Se le puede dar alguna vuelta al proyecto.

    Si necesitas ayuda con cualquier cosa, braséanos por slack Antonio! Si es con regex, con cómo plantear los archivos de funciones, con pandas o lo que sea.

    A por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
