### ISSUE TITLE
[w2-pandas-project] Susana Martin

### ISSUE THREAD

**Issue by Sussi-MW** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#17]
https://github.com/Sussi-MW/data-cleaning-pandas.git

**Comment by breogann** [comment]
Hola Susana! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - No tienes .gitignore! No se te ha colado ningún archivo que no debiera estar ahí, pero para los próximos proyectos asegúrate de incluirlo.
    - Para el resto de archivos, yo sacaría los jupuyter de la carpeta src. Al final no son código fuente como tal, sino una muestra del proceso de trabajo. También puedes numerarlos para que la persona que entre sepa a cuál entrar primero.
    - Genial por haber exportado las gráficas.
- El **[README.md](http://readme.md/) ✍🏻**: lo veo bien. Explicas lo que haces, las hipótesis que tienes y los resultados. Échale un ojo a la sintaxis de markdown para poner títulos, negrita, etc y poder hacerlo más visual.

    Por la parte del objetivo; el objetivo del proyecto es el de dar respuesta a una hipótesis (aunque el aprendizaje sea tu objetivo). 

- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py/) con nombres significativos (limpieza_texto.py) o sea que 👏, era lo que pedíamos.
- El **código 👩‍💻:**
    - Por la parte de los docstrings, además de lo que hace la función, puedes poner lo que recibe y lo que devuelve.
    - Siempre que escribas código muy parecido probablemente se pueda refactorizar. LA función de regex: tiene muchos patrones y tiene muchos ifs. Eso intenta evitarlo. Una forma que se me ocurre es creando diccionarios: las keys pueden ser los patrones y los values lo que tiene que devolver. Así la función sería muy sencilla:

        ```python
        def diccionario ():
        	for j, k in dict.items():
        		if re.match() == j:
        				return k
        		else:
        				return "Other species"
        ```

        en cualquier caso, hacer 28 patrones de regex quizá es una opción demasiado laboriosa. Precisamente lo bueno de la programación es que nos permite hacer tareas muy repetitivas de forma sencilla con poco código. Tenemos que plantear los problemas hacia la automatización.

    - ¿Has trabajado en google colab porque no te funcionaba jupyter?
    - El dropeo de los valores nulos es algo troncal que creo que es mejor hacerlo antes de plantear las hipótesis; en la limpieza general y luego hacer limpieza según hipótesis.
    - En esta función:

        ```python
        def apply_filters(df):
            return df.apply(new_values_species, axis=1)
        ```

        la idea es definir la función y luego pasarle un apply; pero no incluir el apply dentro de la función y luego pasársela el dataframe, ¿mexplico? la idea es siempre hacer una función que hagas cosas con un elemento y luego pasárselo a todos (for, aplpy, map, etc). Cualquier cosa me dices.


    A por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
