### ISSUE TITLE
[w2-pandas-project] Bertrán Gil de Santivañes

### ISSUE THREAD

**Issue by Bertrangsf** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#18]
Está sin terminar... 😢
https://github.com/Bertrangsf/Sharks.git

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks Bertrán 🦈🦈

Hola Bertán!!! Ya estoy por aquí con las correcciones del proyecto de tiburones. 

## Readme

Es condición INDISPENSABLE para presentar el proyecto. Que ha pasado con el Readme!!!! EL principal objetivo de este fichero es una guía rápida para los que van a ver tu proyecto y para saber como usar tu código. **Tips** importantes para esta parte del proyecto, que vaya al grano, sea conciso y muy muy claro. 

Es lo que la gente va a ver de ti! 


## Estructura del repositorio

Vamos a por la estructura del repo: 

- Tienes el fichero de los datos puesto en tu repo! ⚠ Es super importante que cuando usamos bases de datos de kaggle no pongamos en nuestros repos ⚠. Esto es así por que kaggle lo pide claramente, quieren que los datos se descarguen de su base de datos. ¿Qué puedes hacer?

    - Meterlo en el .gitignore
    - No subirlo a tu repo
    - Siempre puedes poner el link a la página de kaggle donde se lo pueden descargar. 

- En caso de que quieras tener tu .csv con los datos limpios puedes crearte una carpeta nueva que sea Data donde vayas guardando todos los ficheros limpios. Esto es principalmente para que no estén pululenado por el repo sin ningún orden. 

- En cuanto a los jupyter, lo mismo, los puedes meter en otra carpeta a la que puedes llamar 'Notebooks' o 'Analysis'. El nombre es un tema un poco más personal, pero si los metes en otra carpeta sería perfecto!

- El `.gitignore`, lo tienes creado pero no tienes nada metido dentro! En este fichero debes meter todos aquellos ficheros que no son necesarios en tu proyecto como por ejemplo los `.ipynb_checkpoints`, `__pycache__` o el ficheros de datos de sharks. Todo lo que metas aquí la gente que vaya a ver tu repo no lo verá. 

- Tienes un jupyter en el repo que no tiene nombre (`Untitled.ipynb`), intenta no hacer esto. Es muy poco explicativo. Luego cuando te metes en el jupyter: 

    - Tienes un código que no explicas en ninguna parte
    - Tienes un return pero no tienes ninguna función!

- Usa celdas del markdown para incluir comentarios en el jupyter y para crear un guion a lo largo del jupyter. 

## Síntaxis de código

- Cuando renombras las columnas del dataset lo haces con un diccionario lo cual está bien si el número de columnas es pequeño. Ya con el número que tienes tú se hace un poco duro ponerte hacer todo eso cuando en un par de lineas usando `strip` y `replace` se puede solucionar. 

    ```python
        df_cleaned = df_cleaned.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings

        df_cleaned = df_cleaned.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja
    ```

- Todos los import al inicio del jupyter

- Cuando eliminas valores nulos de la columna de Country no hace falta que pases los Na a 0 y luego elimines las celdas que tienen 0. Hay un método en pandas que te elimina na. 

- Atomiza código lo que tienes aquí se puede hacer en una sola línea:
    ```python
    df = df.drop(["Case_Number"], axis = 1) 
    df = df.drop(["Location"], axis = 1)
    ```
- En el fichero de visualización sigues haciendo limpieza. Intenta evitar esto, toda la limpieza en un jupyter. 

- Sobre las funciones Bertrán, no se puede crear una función como la de `shark`. Es una locura. Dos ideas:
    - Cuando ves que tienes un código altamente repetido te tiene que saltar una alerta de que hay algo mal. ESO HAY QUE ATOMIZARLO MUCHISIMO

    - Regex sirve para encontrar patrones, lo que nos puede ayudar mucho en esta parte del proyecto. Al final es poco útil si ponemos un patrón general y lo vamos a cambiando un poquito. 

## ToDo

- Hacer el readme
- ⚠ ‼ Atomizar código ‼ ⚠ sobre todo en la parte de las funciones
- Repositorios más ordenados
- En general mucho más orden en el repo.
- *Story telling* del proyecto en la parte de la visualización.

Bueno Bertrán te queda mucho trabajo con este proyecto, tienes muchas cosas que mejorar. No te desanimes, sigue trabajando y poco a poco irá saliendo


![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)

**Comment by Bertrangsf** [comment]
Buenas tardes Ana,  He dado el 200% desde el inicio del curso. Tal era el compromiso que apenas he tenido tiempo ni para dormir. Solo habiéndome cogido un día libre me pasa como a otros compañeros, entre los cuales se encontraba Manuel, me está siendo imposible seguir el ritmo. He hablado con compañeros que se han sacado este y otros cursos y su experiencia no es la misma. No acaban de entender el nivel de frustración teniendo en cuenta mi dedicación y capacidades. Habiendo expresado ya mi desmotivación voy con las cosas que he podido corregir de tus comentarios: He subido ya el Readme y limpiado contenido pero no se ni  meter carpetas en el .gitignore ni se bajarme ni subir los mapas/imágenes…. No es que no haya buscado. Seguiré buscando y cuando sepa hacer tanto el añadir carpetas a .gitignore e importar los mapas, haré la tercera parte del proyecto, crear un notebook con las 5 ilustraciones y, acompañarlas de una pequeña respuesta a cada hipótesis.  También será cuando pueda meter las carpetas de data y .ipynb_checkpoints, __pycache__.  Gracias siempre por todo lo que me ayudas, sin ti no estaría ni la mitad de enterado de lo que estoy hoy. ¡¡¡¡Me has sido de gran ayuda!!!! ¡¡GRACIAS!! Bertrán Gil de Santivañes  De: Ana GarcíaEnviado: miércoles, 7 de abril de 2021 20:04Para: Ironhack-Data-Madrid-Marzo-2021/w2-pandas-projectCC: Luis Bertrán Gil de Santivañes Finat; AuthorAsunto: Re: [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project] [w2-pandas-project] Bertrán Gil de Santivañes (#18) 🦈🦈 Proyecto sharks Bertrán 🦈🦈Hola Bertán!!! Ya estoy por aquí con las correcciones del proyecto de tiburones.ReadmeEs condición INDISPENSABLE para presentar el proyecto. Que ha pasado con el Readme!!!! EL principal objetivo de este fichero es una guía rápida para los que van a ver tu proyecto y para saber como usar tu código. Tips importantes para esta parte del proyecto, que vaya al grano, sea conciso y muy muy claro.Es lo que la gente va a ver de ti!Estructura del repositorioVamos a por la estructura del repo:Tienes el fichero de los datos puesto en tu repo! ⚠ Es super importante que cuando usamos bases de datos de kaggle no pongamos en nuestros repos ⚠. Esto es así por que kaggle lo pide claramente, quieren que los datos se descarguen de su base de datos. ¿Qué puedes hacer?Meterlo en el .gitignoreNo subirlo a tu repoSiempre puedes poner el link a la página de kaggle donde se lo pueden descargar.En caso de que quieras tener tu .csv con los datos limpios puedes crearte una carpeta nueva que sea Data donde vayas guardando todos los ficheros limpios. Esto es principalmente para que no estén pululenado por el repo sin ningún orden.En cuanto a los jupyter, lo mismo, los puedes meter en otra carpeta a la que puedes llamar 'Notebooks' o 'Analysis'. El nombre es un tema un poco más personal, pero si los metes en otra carpeta sería perfecto!El .gitignore, lo tienes creado pero no tienes nada metido dentro! En este fichero debes meter todos aquellos ficheros que no son necesarios en tu proyecto como por ejemplo los .ipynb_checkpoints, __pycache__ o el ficheros de datos de sharks. Todo lo que metas aquí la gente que vaya a ver tu repo no lo verá.Tienes un jupyter en el repo que no tiene nombre (Untitled.ipynb), intenta no hacer esto. Es muy poco explicativo. Luego cuando te metes en el jupyter:Tienes un código que no explicas en ninguna parteTienes un return pero no tienes ninguna función!Usa celdas del markdown para incluir comentarios en el jupyter y para crear un guion a lo largo del jupyter.Síntaxis de códigoCuando renombras las columnas del dataset lo haces con un diccionario lo cual está bien si el número de columnas es pequeño. Ya con el número que tienes tú se hace un poco duro ponerte hacer todo eso cuando en un par de lineas usando strip y replace se puede solucionar.·             df_cleaned = df_cleaned.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings·          ·          ·              df_cleaned = df_cleaned.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra bajaTodos los import al inicio del jupyterCuando eliminas valores nulos de la columna de Country no hace falta que pases los Na a 0 y luego elimines las celdas que tienen 0. Hay un método en pandas que te elimina na.Atomiza código lo que tienes aquí se puede hacer en una sola línea:·         df = df.drop(["Case_Number"], axis = 1) ·          df = df.drop(["Location"], axis = 1)En el fichero de visualización sigues haciendo limpieza. Intenta evitar esto, toda la limpieza en un jupyter.Sobre las funciones Bertrán, no se puede crear una función como la de shark. Es una locura. Dos ideas:Cuando ves que tienes un código altamente repetido te tiene que saltar una alerta de que hay algo mal. ESO HAY QUE ATOMIZARLO MUCHISIMORegex sirve para encontrar patrones, lo que nos puede ayudar mucho en esta parte del proyecto. Al final es poco útil si ponemos un patrón general y lo vamos a cambiando un poquito.ToDoHacer el readme⚠ ‼ Atomizar código ‼ ⚠ sobre todo en la parte de las funcionesRepositorios más ordenadosEn general mucho más orden en el repo.Story telling del proyecto en la parte de la visualización.Bueno Bertrán te queda mucho trabajo con este proyecto, tienes muchas cosas que mejorar. No te desanimes, sigue trabajando y poco a poco irá saliendo—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
