### ISSUE TITLE
[w2-pandas-project] Luis Sanchez de Leon

### ISSUE THREAD

**Issue by lsdl13** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#19]
https://github.com/lsdl13/Proyecto.git

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola Luiss 🙋‍♀️ vamos con las correcciones del proyecto de tiburones. Has hecho muy buen trabajo en  este proyecto, has entregado un proyecto ordenado y fácil de seguir, todo muy bien documentado y combinando distintas herramientas aprendidas durante el curso 🚀🚀🚀

## Readme

El readme genial, super sencillo de seguir, muy bien resumido y guiado todo lo que hiciste en el proyecto. Solo como detalle de dejo por aquí un comentario:

-  Muy bien que hayas puesto las librerías que has usado para este proyecto, si ya pones los links que lleven a la documentación oficial de cada página sería la leche. Además, no hace falta que pongas `import pandas as pd`. Poniendo solo pandas sería suficiente, pero vamos que esta de 10 el readme!. 


## Estructura del repositorio

El repo en general lo tienes muy bien organizado, esta muy muy bien. Te dejo por aquí unos comentarios de detalles:

- El `.gitignore` muy bien, lo has creado y has metido ahí la mayoría de los ficheros que había que meter. Recuerda que el archivo de sharks no debemos dejarlo en el repo por lo que lo puedes meter en el `.gitignore` y se te coló un `DS_Store`. 

- Los jupyters numerados, muy bien ayuda a seguir el *workflow* del trabajo. Para un futuro, puedes meter estos ficheros en otra carpeta y que queden todos juntos. 

- El archivo de `functions.py`, no lo llames `functions`!!! Ponle un nombre más descriptivo. Además, esta vacío, intenta no poner en tu repo ficheros vacíos, puede generar confusión, se te olvidó quitarlo o es que en ese `.py` debería haber algo y no se actualizo?


## Sintaxis de código

Vamos a por el código:

- Los import siempre al inicio del jupyter, incluso los del `.py` con las funciones que creaste.  

- No hace falta que uses el `display`y el `print`. 
  ```python
      display(df.head())
      print(df.shape)
  
      df.head()
      df.shape
  ```

- Cuando reasignas el nombre de algunas columnas para quitar los espacios, como lo haces creando un diccionario esta perfecto. Si bien, para este caso se puede hacer, imagina que tienes un dataframe con 30 columnas a las que a todas les tienes que quitar un espacio. Usar un diccionario puede ser poco eficiente. Te dejo por aquí unas líneas de código por si te aportan valor con otra posible opción. 

    ```python
    # Como lo hiciste con el diccionario 
    
    df.rename(columns={"Case Number": "Case_Number", 'Sex ': 'Sex', "Fatal (Y/N)": "Fatal?", "Species ": "Species",
                   "Investigator or Source": "Investigator_or_Source", 'href formula': 'href_formula',
                   "Case Number.1": "Case_Number_1","original order": "original_order", "Unnamed: 22": "Unnamed_22",
                   "Unnamed: 23": "Unnamed:_23", "Species ": "Species"}, inplace=True)


    # Otra opción
    df_cleaned = df_cleaned.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings

    df_cleaned = df_cleaned.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja

    ```

- Cuando limpias la columna de `Fatal` como tu lo hiciste esta bien, pero si te fijas repites la misma estructura de código varias veces. Cuando eso pasa... hay que atomizar código! En este caso te podrías haber creado una función con un bucle para simplificarlo un poco. Lo mismo pasa con la función `set_values` intenta ver como se podría atomizar un poco ese diccionario. Lo podrías hacer con regex. Si no te ves muy claro lo vemos vale?  

- En la columna de `Year`, entiendo que lo que quieres hacer es quedarte con los años desde 1900. Lo haces en dos pasos, pero... porque no lo haces en uno?
  ```python
  #COMO LO HACES TÚ
  noAS=df_lethal[df_lethal['Year'] < 1900].index # te quedas con los datos anteriores a 1900
  
  df_lethal.drop(noAS, inplace=True) # los datos anteriores los restas del dataframe original
  
  #PERO ESTO LO PUEDES HACER EN UN PASO SELECCIONANDO LOS DE 1900 EN ADELANTE!
  noAS=df_lethal[df_lethal['Year'] > 1900].index
  ```
- EL `lethal_diccionary` hay que hacer algo con ese diccionario, hay que atomizar a tope va?? Si quieres lo vemos!

- Cuando vas a seleccionar aquellos países que aparecen más de 5 veces, como lo haces esta bien, pero si te fijas estas usando 4 líneas de código cuando en realidad lo puedes hacer con una usando un `groupby`. Te dejo por aquí código por si te aporta valor: 
    ```python
    df_Country[df_Country.groupby('Country')['Country'].transform('size') > 5]
    ```
- Vamos con el tercer jypyter cuando sacas las velocidades. Entiendo que lo que quieres hacer es seleccionar todo lo que no sea 1, 2 o 3 y por eso usas la virgulilla(~). En realidad este es un operador muy poco usado en pandas. Recuerda que tienes `=!` que es más universal. 

- Super bien todas las gráficas que sacaste Luis! Se nota que has entendido los datos y los has intentado explotar al máximo!

## ToDo

En general has hecho un buen trabajo con este proyecto Luis. Te dejo por aquí algunas cosas para el futuro que podrías cambiar, pero en general, enhorabuena!!

- Atomizar ese código en algunas fases de la limpieza como en la columna `Fatal`

- Se te han colado funciones en el jupy, intenta llevarlas todas a el archivo .py

- Limita los `print()` cuando el output es muy largo, es simplemente para no distraer la atención de la gente que este viendo tu repo

- Para el futuro, intenta hacer una limpieza en un único fichero y genera un único .csv!

- Me ha faltado un poco de fantasía en el *story telling* o intentar relacionar más las hipótesis entre ellas, tal cual las tenias planteadas casi se van dando paso las unas a las otras. 

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
