### ISSUE TITLE
[w2-pandas-projec]Alberto Pérez

### ISSUE THREAD

**Issue by asiokfd** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#20]
https://github.com/asiokfd/data-cleaning-pandas/issues

**Comment by breogann** [comment]
Hola Alberto! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

Nos has pasado el enlace de una issue que te has hecho tú a tu propio proyecto, creo que tasliao un poco, pero no pasa nada. Para la próxima, con que nos des el enlace a tu repo directamente, nos vale 🙂

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - No se te han colado archivos temporales pero has incluido el archivo de Kaggle. Recuerda que los autores piden que no se suba. Tendrías que borrarlo del caché de git, incluirlo en el git ignore y hacer el add, commit y push de nuevo.

            ```python
            git rm --cached elarchivo
            ```

            también se te ha colado una carpeta de .vs en src. 

    - El resto de la organización la veo bien.
    - Ah! Y dentro de src tienes archivos de texto. Eso iría fuera también.
- El **[README.md](http://readme.md/) ✍🏻**:
    - No se te renderiza el markdown como títulos porque tienes que poner espacios entre las almohadillas y los números.
    - Revisa alguna cosa, tipo 👀:

        ```python
        #1. hipotesis: los surferos provovan mas atáques que los surferos
        ```

    - "que he leido que es donde hay mas concentracio" estaría genial si puedes enlazar la fuente
    - Por lo demás, lo veo genial. Has explicado lo que has hecho, lo que has utilizado, la organización del repositorio y cuáles eran tus hipótesis.
- La **modularización 📉**: Está genial que lo hayas separado por temática. Pero en limpieza_texto.py tienes líneas de código, y lo que nos interesa es que haya funciones. Si hay funciones definidas, se pueden importar en otro sitio y aplicar. Lo mismo con la parte de visualización: la idea es encapsular código. Meter lo que hemos picado en funciones para luego llamarlas desde otro sitio.
- El **código 👩‍💻:**
    - Genial por ir comentando tu propio código 👏
    - En el jupyter de preliminary no se te renderiza la imagen por la ruta:

        ```python
        "![texto_descriptivo](portada.jpg)"
        ```

    - Si has importado funciones desde otro sitio, acuérdate de eliminarlas luego del jupyter:

        ```python
        def reduciendo (x): #unica funcion de momento
            for item in x:
                if "surf" in x:
                    return "Surfing"
                if "Surf" in x:
                    return "Surfing"
                else:
                    return "Fishing"
        ```

    - Te falta un jupyter a modo de story-telling para hacer resumen de las hipótesis con la visualización
    - La forma de buscar si reunión o seychelles está en los países, quizá es un poco forzada. Puedes hacer una lista (o un diccionario) con las posibilidades de escritura y entonces iterar por la lista de valores únicos. Así no tienes que hacer varias celdas para varios booleanos. Tenemos que buscar siempre la forma de no poner líneas de código parecidas: eso será un indicador de que podemos refactorizar.
    - Cuidado con la visualización de la última hipótesis. No se puede interpretar la gráfica porque no se ven ni los datos ni las etiquetas del eje X.

    Si necesitas ayuda con cualquier cosa, braséanos por slack Alberto! Si es con regex, o con cómo plantear los archivos de funciones o lo que sea. 

    A por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
