### ISSUE TITLE
[w2-pandas-projec]Pablo Fernández Cañete

### ISSUE THREAD

**Issue by pfernancanete** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#21]
https://github.com/pfernancanete/Shark-study

**Comment by breogann** [comment]
Hola Pablo! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - No se te han colado archivos temporales pero has incluido el archivo de Kaggle. Recuerda que los autores piden que no se suba. Tendrías que borrarlo del caché de git, incluirlo en el git ignore y hacer el add, commit y push de nuevo.

            ```python
            git rm --cached elarchivo
            ```

    - El resto de la organización la veo bien.
- El **[README.md](http://readme.md/) ✍🏻**: Has explicado lo que has hecho, lo que has utilizado, y cuáles eran tus hipótesis. Si quisieras completar más, puedes añadir alguna gráfica de las que has generado.
- La **modularización 📉**: tienes una función en uno de los archivos (sin docstring, recuerda que es importante!) y luego tienes el archivo de visualización vacío.
- El **código 👩‍💻:**
    - Genial por ir comentando tu propio código. Los jupyters están muy guiados.
    - Para la visualización de las actividades por año, quizá puedes utilizar un plot linear; el relplot no es muy interpetable.
    - Si tienes errores, no los dejes imprimidos en el jupyter!
    - Lo que tienes está bien, pero podrías plantear alguna hipótesis más para hacer algo más de limpieza 😕

    Si necesitas ayuda con cualquier cosa, braséanos por slack Pablo! Si es con regex, con cómo plantear los archivos de funciones, con pandas o lo que sea.

    A por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
