### ISSUE TITLE
[w2-pandas-project] Cristina Callejo

### ISSUE THREAD

**Issue by CristinaCallejo** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#22]
[EDA Sharks with pandas](https://github.com/CristinaCallejo/EDA-Sharks-with-pandas)

Una gozada meterse en el dataset, he profundizado un montón pero, por ello, me han faltado 1 o 2 días para completarlo! Me he quedado a medio camino :(

Lo acabo esta semana :))))

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola hola Cris!! Vamos a por la corrección del proyecto de tiburones!!! 
## Readme / los readme 

Menudo currazo te has marcado aquí amiga!!!! Esta super bien, pero de dejo por aquí unos tips por si te pueden ser útiles en el futuro:

- Controla un poco la longitud, recuerda que el readme es un pequeño manual de uso y contexto de lo que esta dentro del repo. Si quieres hacer documentaciones más detalladas puedes usar otras herramientas como [gitbook](https://www.gitbook.com/) y luego la citas en tu readme. Pero en github vete al grano!

- Sería top que cuando citas lo documentación que usas pusieras un link a la documentación oficial de las librerías. 

- Intenta unificar los tres que tienes en uno único. Facilita la lectura al usuario que vaya a ver tu repo. 



## Estructura del repositorio

- Mezclas en una carpeta imágenes y los ficheros .csv. Para que quede perfecto, crea dos carpetas independientes, una para las imágenes y otra para los datos. 

- El `.gitignore` perfectito no se te pasó ningún fichero por ahí!

- En cuanto a los jupyter, solo por ponerme un poco tiquismiquis, los puedes meter en otra carpeta a la que puedes llamar 'Notebooks' o 'Analysis'. El nombre es un tema un poco más personal, pero si los metes en otra carpeta sería perfecto! Además, todos los ficheros numeraditos para seguir el *Workflow* genial!

- En las funciones me faltó el docstring (que es lo que hace la función, que es lo que recibe, que tipo tienen los parámetros que recibe la función y lo que nos devuelve).

- Algunas funciones de las que has creado están genial (`import_csv`, `remove_unnecessary_columns`), peerooo la clave de las funciones es crear nuestras propias funciones que estructuren código de forma más legible y reutilizarlas en partes que se repiten mucho. Crear una función para un `read_csv` que vamos a hacer en una línea no es lo ideal. Pero esta bien que te hayas arrancado, este proyecto no es el mejor para volverse loco con las funciones. 

- En el segundo jupyter, tienes tres datasets 🔝. Como detalle, durante todo el jupyter vas intercalando limpieza de los tres datasets. Puede resultar un poco confuso de seguir, cuesta a veces saber sobre que dataset estas trabajando. 


## Síntaxis de código

- En estas líneas de código: 
    ```python

    df2019['fatal'] = df2019['fatal'].replace(['N','Y','UNKNOWN',' N','F','2017','y','M','Y x 2','N '],['NO','YES','UNKNOWN','NO','YES','INVALID','YES','INVALID','INVALID','NO'])
    ```
    Hay algunas combinaciones que las podrías quitar si antes haces un `strip`. Aquí una función hubiera siendo perfecto, simplificando el código. Podría ser algo como esto, atomizando un poco el código: 
    ```python
    def injury(x): 
        x = str(x)

        if (x == "M") or (x == "UNKNOWN") or or (x == "2017") or (x == "Y x 2):
            return np.nan
        elif (x == "Y"):
            return "YES"
        elif (x == "N"):
            return "NO"
    ```

- Esta función:
    ```python
    def import_xls_to_csv (string):
        string_csv = string.replace('.xls','.csv')
        read_file = pd.read_excel (string)
        read_file.to_csv (string_csv,
                    index = None,
                    header=True)
        dataframe = pd.DataFrame(pd.read_csv(string_csv))
        #print("dataset imported to .csv, assigned to variable: 'dataframe', please call function again by assigning it to 'dataframe'")
        return dataframe
    ```
- Importas los dataset con la función que creas lo cual esta super bien, pero las vuelves a llamar: 

    ```python
    dataframe_GSFA = f2.import_csv("data-processed/attacks_updated_v1.csv")
    df1 = dataframe_GSFA.copy()
    ```
    Luego trabajas con df1, df2 y df3. En realidad es poco eficiente en cuanto a código, haces lo mismo dos veces. 

## ToDo

- Los doctrings en las funciones

- Los ejes de las gráficas, se ven un pelín mal. Estaría genial que eso lo pudieras dar una vueltita

- Visualización y *story telling* en el jupyter para cerrar la historia que presentas. 

- Vale Cris el proyecto esta bien y te has metido una buena currada buscando información adicional. Hubiera estado bien que terminaras el proyecto. Cuando entras en un tema que te motiva a veces es difícil poner focus en el objetivo principal y no desviarse. Hubiera estado bien que terminaras la parte "obligatoria" del proyecto (por ejemplo la visualización) y que luego te pusieras con la fantasía adicional.

En general, has hecho un buen proyecto Cris 🚀🚀

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
