### ISSUE TITLE
[w2-pandas-project] Darío Contreras

### ISSUE THREAD

**Issue by DarioCMasedo** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#23]
https://github.com/DarioCMasedo/Pandas-project

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola Darío 🙋‍♀️ vamos con las correcciones del proyecto de tiburones:

## Readme

En general esta muy bien, corto y conciso dejando claro cual es el objetivo del proyecto. Te dejo por aquí unos comentarios por si te aportan valor y los puedas incluir en próximos proyectos: 

- Dado que por política de kaggle el fichero no debería estar en tu repo estaría muy bien que añadieras un link de la página donde la gente que vea tu repo se lo pueda descargar. 

- Pusiste una pequeña descripción de cada de una de las librerías que has usado, bien! Como detalle por ponerme fina fina, podrías poner un link que lleve a la página oficial de cada una de las librerías. 

- Me falta un poco una descripción del dataset que vas a usar en el proyecto. De que va, que datos nos da, y hacer un pequeño resumen de los pasos que has ido haciendo durante todo el proyecto. 

## Estructura del repositorio

Muy bien organizado el proyecto, te dejo por aquí unos comentarios por si te ayudan: 

- Se te quedó fuera de la carpeta data el fichero .csv con tus datos limpios. 

- El `.gitignore` muy bien!!! No se te escapo ningún fichero raro ni que no se debiera ver!

- Archivo `visualización.py` esta vacío. En este caso, es mejor no subir archivos que están vacíos. Pueden generar confusión, está vacío porque no subiste la última versión o porque no has hecho nada en ese fichero?

## Sintaxis de código

Muy bien cada paso comentado con celdas de jupyter. Vamos a por más cosas de sintaxis de tu código:

- Entre las importaciones tienes una importación a un fichero de funciones (`limpieza_texto.py`), pero... ese fichero no esta en tu repo!!! 👀🙈

- Perfecto que antes de eliminar una columna veas lo que contiene para ver si nos interesa o no. 

- Cuando reasignas el nombre de algunas columnas para quitar los espacios, como lo haces creando un diccionario esta perfecto. Si bien, para este caso se puede hacer, imagina que tienes un dataframe con 20 columnas a las que a todas les tienes que quitar un espacio. Usar un diccionario puede ser poco eficiente. Te dejo por aquí unas líneas de código por si te aportan valor con otra posible opción. 

    ```python
    # Como lo hiciste con el diccionario 🔝
    data = data.rename(columns={'Fatal (Y/N)':'Fatal',
                           'Species ': 'Species'})

    # Otra opción
    data = data.columns.str.strip() # elimina todos los posibles espacios al inicio o al final de los strings

    data = data.columns.str.replace(' ', '_') # sustituye los espacios en blanco en los strings por la barra baja

    ```
⚠ En general has hecho una limpieza muy superficial de limpieza. Has quitado columnas y filas que no interesaba tener el dataset y cambiado el nombre de las columnas. Pero no te has metido en el barro de la limpieza que era el objetivo principal de este proyecto. Por ejemplo, la columna `Fatal` no tenía unicamente `N` y `Y`, ¿qué tendrías que haber hecho? unificar todos los valores de esa columna para evitar que te salieran varias N cuando hacias las gráficas. Para la columna de `Year` si haces un `unique` verás que tienes valores de años y otros que son letras. Tendrías que haber eliminado esos datos que eran "raros" para cada una de las columnas que eran importantes para tus hipótesis.


## ToDo

Bueno Darío, has pasado un poco por encima de uno de los objetivos clave del proyecto. Te recomiendo que te metas un poco más a fondo en esta limpieza. No te desanimes! este dataset estaba muy muy sucio y hay que pelearse mucho con pandas para que este limpio. Dale una vueltita vale?? 

Si tienes alguna duda por aquí estoy, no dudes en preguntarme!!!

![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
