### ISSUE TITLE
[w2-pandas-project]  Bertrán

### ISSUE THREAD

**Issue by Bertrangsf** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#3]
https://github.com/Bertrangsf/First-Proyect-Sharks

**Comment by Bertrangsf** [comment]
https://github.com/Bertrangsf/First-Proyect-Sharks

**Comment by AnaAGG** [comment]
Bertrán cierro esta issue, pero tu sigue dándole con los comentarios que te hice
