### ISSUE TITLE
[w2-pandas-project] Emilio

### ISSUE THREAD

**Issue by emilio-carrasco** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#4]
https://github.com/emiliocarrascomoreno/sharkstattack

**Comment by breogann** [comment]
Hola Emilio! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: no se te han colado archivos temporales, o sea que perfecto. Y los tienes ignorados de forma recursiva.
    - Genial por haber exportado las gráficas.
    - Para la organización de carpetas y la distribución de los jupyters: las carpetas están bien, pero tienes archivos de python y jupyters en la root. También tienes archivos que son readme pero son jupyters?
        - Agrúpalos; los .py en la src y los jupyters pueden o bien ir a una carpeta de notebooks, o bien puedes numerarlos. Al final siguen un orden lógico: exploración, limpiea, visualización, story-telling, etc.
    - También has dejado los archivos que dejamos a modo de plantilla de la carpeta de src.
- El **[README.md](http://readme.md/) ✍🏻**: no tienes. Has cogido el nuestro; tienes que sustituirlo!
- La **modularización 📉**: no hay nada modularizado Emilio. Has copiado y pegado las líneas de código de los jupyters en archivos.py, pero tienen que estar metidos dentro de funciones. O sea, la idea:
    - Probar código en jupyter
    - Cuando funciona, llevarlo a los .py y meterlos en funciones
    - Esas funciones, importarlas de nuevo al jupyter

    Entiendo que lo que has hecho es hacer ejecutables, ¿no?

- El **código 👩‍💻:**
    - En los jupyters, cuando utilizas las funciones, las importas desde lt. Pero en lt no tienes nada. ¿?
    - Las importaciones hazlas siempre al principio del jupyter
    - Procura no dejar los errores impresos

    Mañana (lunes) lo miramos, ¿vale?, a ver si hay algo que se me está escapando. Pero sobre todo la parte formal (organización del repo y del código) está un poco caótica; luego lo vemos. 

    Ahora, a por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
