### ISSUE TITLE
[w2-pandas-project] Jacobo Martín-Cubas Núñez

### ISSUE THREAD

**Issue by marcunu** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#5]
https://github.com/marcunu/Shark_Attack.git

**Comment by breogann** [comment]
Hola Jacobo! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

¿Por qué te aparece tu usuario de github como marcunu pero luego todos los commits hechos como `"Jhon` 👀?

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: perfect. No se te ha colado ningún archivo que no tuviera que estar ahí.
    - Los commits, intenta ponerles nombres significativos. Si en algún momento necesitaras volver a alguno de ellos, no sabrías en cuál hiciste el qué.
    - Te dejo esto, por si le quieres echar un ojo: pipreqs [https://pypi.org/project/pipreqs/](https://pypi.org/project/pipreqs/). Para este proyecto no lo pedimos, para los siguientes probablemente sí.
- El **[README.md](http://readme.md/) ✍🏻**: está genial. Puedes añadir enlaces a las librerías y quizá alguna gráfica que hayas exportado o alguna idea de cómo estaban los datos antes de que los procesaras.
- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py/) con nombres significativos (limpieza_texto.py) o sea que 👏, era lo que pedíamos.
- El **código 👩‍💻:**
    - La limpieza preliminar de dropear columnas y valores nulos, lo puedes hacer en un mismo dataframe, en vez de crear varios. Al menos en el caso de esta limpieza preliminar.
    - Las importaciones al principio Jacobo! aunque sean de tus propias funciones
    - En esta función:

        ```python
        def elim_vacias(df, new_df, ax, hw):

            new_df = df.dropna(axis=ax, how=hw)

            return new_df
        ```

        has parametrizado new_df, pero es algo que luego defines como nuevo dentro de la función, ¿no? O sea, a la hora de llamar a esa función, ese argumento no se lo estás pasando. 

    - Los import siempre van fuera de las funciones 🔪:

        ```python
        def df_filtered_best(data_frame, columna, n_ind):
            import pandas as pd
        ```

        si haces un apply con esa función, vas a importar pandas 60.000 veces. (que además, si se lo estás pasando a un dataframe que ya tienes cargado, ya estará importada en otro sitio, ¿no?)

    - Genial por meter los docstrings
    - Esta función:

        ```python
        def rotar_labels(grafico, angulo):
            grafico.set_xticklabels(grafico.get_xticklabels(), rotation=angulo)
        ```

        la tienes en el archivo de limpiez.py.

    - Otra cosa que puedes hacer a la hora de definir las funciones es, en vez de recibir como parámetro el dataframe, puedes hacer una función sencilla y hacer df.apply (sin seleccionar la columna entre medias, pero sí como argumento de la función).
    - Si tienes errores impresos, elimina esa celda. No subas algo a modo de borrador. Recuerda que esto ces como vuestro portfolio.
    - Para los investigadores, ¿estás teniendo en cuenta que un mismo investigador esté en varias celdas? En algunos estará como autor principal, en otros estará como co-autor, etc. Además, miras los valores únicos pero hay más info además de nombre y apellidos: ej.: 6/20/2002. Entonces puedes utilizar un regex que te busque palabras que empiecen por mayúscula, que vengan después de un espacio, etc.
    - Puedes también hacer una limpieza de los nombres de las columnas: quitar espacios, pasar a minúscula, etc.
    - Aquí:

        ```python
        b = shrk[shrk["Species "] == "Bull shark"]
        ```

        estarías dejando datos fuera si buscas por coincidencia exacta. 

    - Para poner temazos:

        ```python
        import webbrowser
        url = 'https://www.youtube.com/watch?v=KybAvaM3b90'
        webbrowser.register('chrome',
        	None,
        	webbrowser.BackgroundBrowser("C://Program Files (x86)//Google//Chrome//Application//chrome.exe"))
        webbrowser.get('chrome').open_new(url)
        ```

        puedes hacerlo con python, pero también te vale:

        ```python
        !open https://www.youtube.com/watch?v=dQw4w9WgXcQ
        ```

        en una celda de jupyter 😜

    - Para la visualización:
        - Esta gráfica: If we consider each species individually, these are the activities that have been damaged by sharks., quizá no es muy explicativa; pero el resto las veo bien.

    Tienes un proyecto bien planteado, pero te faltan algunas cosas formales. Dale una vuelta si tienes tiempo, si no, tenlo en cuenta para el siguiente proyecto. Aun así, buen trabajo! 💪

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
