### ISSUE TITLE
[w2-pandas-project] Pablo FR

### ISSUE THREAD

**Issue by fromeropablo** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#6]

**Comment by fromeropablo** [comment]
https://github.com/fromeropablo/Project-week_02

**Comment by AnaAGG** [comment]
# 🦈🦈 Proyecto sharks 🦈🦈

Hola hola Pabloo!! Vamos a por la corrección del proyecto de tiburones!!! 

## Readme

- Muy buen trabajo con el Readme Pablo,  invita a seguir leyendo, fácil de seguir y resumiendo muy bien todo el trabajo realizado. Captas la atención del lector desde el primer momento. 

- Las hipótesis que planteas, están muy bien todas. Además das un poco de contexto a cada una de ellas, explicando que te ha llevado a plantearte estas hipótesis. Muy buen trabajo en este sentido Pablo!!!

- Me ha faltado un poco de descripción de la base de datos, como un pequeño resumen en dos líneas. 

- Para que fuera la leche del todo, estaría genial que cuando listas las librerías que has usado añadas el link a la documentación oficial. La carpeta `src` donde tienes las funciones que has creado no hace que la incluyas en el listado de librerías, date cuenta que no es una librería. 

- Hay que mirar que está pasando con esas imágenes que no se cargan en el readme!! 👀


## Estructura del repositorio

- El archivo `.gitignore` perfecto. Has metido la base de datos. Solo como detalle, se te han pasado dos archivos que deberían ir también en el gitignore `__pycache__` y `.ipynb_checkpoints`. 

- Suuuper las funciones con sus docstrings. Lo ideal sería que pusieras que parámetros recibe la función y de que tipo son. Si lo tienes todo en inglés, pon los nombres de los ficheros en inglés (se te paso el de `limpieza_texto.py`) Por ponerme fina fina por convención los docstring van antes del código:

    ```python
    def first_drop(data):
    """
    Remove all the rows which contain only missing values.
    """
        data.dropna(axis = 0, how = "all", inplace = True)
    ```

- Los jupyter, super bien, numerados para que sea fácil de seguir el workflow de trabajo que has seguido. Solo como detalle, los jupyters también los puedes meter en una carpeta y ya queda suuuper ordenado.  

- Al final lo que haces es crearte tres dataset independientes para hacer la visualización. Lo ideal es que lo tuvieras todo en un único .csv y sobre este lo vayas trabajando todo. 


## Sintaxis de código

- Vamos con las funciones, has creado tres funciones. Pero ninguna tiene return! Recuerda que una función sin return te va a devolver `None`. 

- En general las funciones están bien, son pequeñas con objetivos específicos, genial. Peeero... una de las utilidades de las funciones es que sea generalizables, es decir, que te valgan para este dataset o para otros. En tu caso las dos últimas funciones son exclusivas para tu dataset... 😥

- Detallito, en el segundo jupyter se te paso una función en el jupyter, recuerda siempre al archivo .py

- Buen trabajo añadiendo valor a tu dataset con otro dataset.

- Venga vamos a darle a esa columna de Date. Entiendo que hiciste el regex para limpiar esa columna y quedarte solo con la fecha (día-mes-año), para luego quedarte con el mes. Te dejo por aquí unas líneas de código por si te ayuda. 

    ```python 
    string = "Reported 19-Dec-1950" 
    patron = r'(\d{2})-(\w{3})-(\d{4})' # sacas las fechas con esta estrutura 01-Dec-1989

    patron_seasons = re.search(patron, string) 
    patron_seasons[0].split("-")[1]
    'Dec'
    ```
Si esto lo metes en una función y un apply como lo tienes te debería tirar. Si te quedan dudas dímelo y lo vemos!

- En la visualización, igual que te creas una función para limpiar el dataset también te la podrías haber creado para las figuras. Un buen ejemplo es la última figura que tienes en el jupyter de visualización. Además, cuando veas que tienes estructuras de código que se repiten muchas veces... a atomizar! Se puede usar por ejemplo un `for`. Dale una vueltita a esto y si ves que no te sale dimelo y lo vemos!

## ToDo
Te pongo por aquí un par de detallitos que podrías cambiar para darle más valor a tu trabajo:

- Explicación con markdown en el jupyter de visualización. Me ha faltado un poco de *story telling* en el jupyter de visualización, vender un poco más tu historia metiendo "fantasía" a modo de explicación de los gráficos. Lo has hecho durante todo el proyecto  faltó aquí 

- En el readme, algún detalle más sobre los pasos que has ido dando en la limpieza. 

- Atomizar ese código de la visualización 

En general buen trabajo Pablo, sigue trabajando así que estas en el 🚀🚀🚀!


![image](https://media1.popsugar-assets.com/files/thumbor/AhGzlEOD5gvnrypTxSVVk30xmZM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/08/11/763/n/1922507/99fb45c4a9851709_tumblr_m8f2cpVRoo1rv7kpdo1_1280/i/Beatles-Fan.jpg)
