### ISSUE TITLE
[w2-pandas-project] Julieta Staryfurman

### ISSUE THREAD

**Issue by julistary** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#7]
https://github.com/julistary/pandas_project.git

**Comment by breogann** [comment]
Hola Julieta! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - Se te han colado archivos temporales como el .DS_Store (es un arhicvo que genera el Finder en Mac para indexar archivos). No lo tienes añadido en el gitignore. Además, has subido el archivo de Kaggle, que los autores piden que no se suba 🔪

            Lo que tienes que hacer es primero es hacer que git destrack-ee los archivos. 

            ```
            git rm --cached .DS_Store
            ```

            (o de forma recursiva, tal y como lo tenemos nosotros en los labs). Luego guardarlo en el .gitignore y volver a repetir el proceso de add, commit y push.

    - Para la organización de carpetas y la distribución de los jupyters, está perfecto. Igual con la modularización del archivo de funciones. ¿El archivo de limpieza,py está vacío?
    - Te dejo esto, por si le quieres echar un ojo: pipreqs [https://pypi.org/project/pipreqs/](https://pypi.org/project/pipreqs/). Para este proyecto no lo pedimos, para los siguientes probablemente sí. Es en la línea de lo que hablábamos ayer de los entornos (te genera el requirements.txt automáticamente).
    - Genial por haber exportado las gráficas.
- El **[README.md](http://readme.md/) ✍🏻**: lo veo bien. Explicas lo que haces, las hipótesis que tienes y los resultados.
- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py/) con nombres significativos (limpieza_texto.py) o sea que 👏, era lo que pedíamos (quitando ese archivito vacío)
- El **código 👩‍💻:**
    - Las docstrings están muy top.
    - Aquí

        ```python
        return [value for value,freq in dict_.items() if freq > min_]
        ```

        genial por la comprehension list. Lo único es que dices que devuelve un diccionario. Te devuelve un diccionario dentro de una lista, ¿no?

    - "#I know that no libraries are imported into the functions but it was the only way to make it work." A puntito estaba de decírtelo. ¿No te dejaba importarlo en el jupyter?
    - En esa misma función devuelves:

        ```python
        return("not found")
        ```

        que es una string. Pero puedes hacer que te devuelva "np.nan", que es un objeto de python con el que puedes trabajar.

    - Para el renaming de las columnas:

        ```python
        df.rename(columns = {"Case Number" : "Case_Number", "Species " : "Species", "Sex " : "Sex", "Fatal (Y/N)" : "Fatal"}, inplace=True)
        ```

        igual te resulta más cómodo utilizar métodos de python como .strip() o .lower()

    - Primero eliges un subset:

        ```python
        df.dropna(axis = 0, how="all",subset=['Date', 'Year', 'Type', 'Country', 'Area', 'Location',
               'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal', 'Time', 'Species',
               'Investigator or Source'],inplace=True)
        ```

        y luego dropeas las columnas:

        ```python
        df.drop(['Case Number.1', 'Case Number.2', 'Unnamed: 22', 'Unnamed: 23','pdf','href formula','href','original order'], axis=1, inplace = True)
        ```

        si lo haces al revés, te ahorrarías el paso de elegir el subset, no?

    - En general, muy buen manejo del código. Exploras varias técnicas (map, lambda, apply) 👏
    - Está bien que vayas exportando los datasets según vas filtrando la información. Pero ¿quizá no te interesa hacer la limpieza entera y tener un mismo dataset para todas las hipótesis?
    - Buenos patrones de regex también!
    - Creo que has hecho una muy buena elección de los gráficos y has utilizado los que te han hecho falta para la hipótesis que tenías.
    - Para la parte de story telling no es necesario que entres en detalles técnicos. Es como si es lo estuvieras enseñando a alguien que no sabe de código ni lo que es un diccionario.

    Buen trabajo Julieta 💪 Está muy bien el proyecto; sólo esos detalles que te comento.

    A por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
