### ISSUE TITLE
[w2-pandas-project] Unai Arteaga 

### ISSUE THREAD

**Issue by Unaiat** [Ironhack-Data-Madrid-Marzo-2021/w2-pandas-project#8]
https://github.com/Unaiat/Shark_Attack_Project

**Comment by breogann** [comment]
Hola Unai! 🙋‍♂️ 

Voy a intentar darte todo el feedback que pueda; no tanto por cosas que haya mal, sino porque cuanto más input, mejor puedes dejar el proyecto.

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:
        - Se te han colado archivos temporales como el .__pycache__  No lo tienes añadido en el gitignore.

            Lo que tienes que hacer es primero es hacer que git destrack-ee los archivos. 

            ```
            git rm --cached .__pycache__
            ```

            (o de forma recursiva, tal y como lo tenemos nosotros en los labs). Luego guardarlo en el .gitignore y volver a repetir el proceso de add, commit y push.

            También tienes un .DS_Store dentro de la carpeta de data.

    - Para la organización de carpetas y la distribución de los jupyters, está perfecto. Igual con la modularización del archivo de funciones. Lo único, se te ha colado un csv en la root de tu proyecto, ¿no? También, quizá puedes numerar los jupyters para que sea incluso más explícito y la persona que entre sepa a dónde ir lo primero.
    - Te dejo esto, por si le quieres echar un ojo: pipreqs [https://pypi.org/project/pipreqs/](https://pypi.org/project/pipreqs/). Para este proyecto no lo pedimos, para los siguientes probablemente sí. Es en la línea de lo que hablábamos ayer de los entornos (te genera el requirements.txt automáticamente).
    - Genial por haber exportado las gráficas.
- El **[README.md](http://readme.md/) ✍🏻**: lo veo bien. Explicas lo que haces, las hipótesis que tienes y los resultados. Por añadir, puedes incluir las librerías que has utilizado (con enlaces a la documentación).
- La **modularización 📉**: ¿somos súper pesados con esto? sí. Has separado las funciones del jupyter y las has llevado a [archivos.py](http://archivos.py/) con nombres significativos (limpieza_texto.py) o sea que 👏, era lo que pedíamos.
- El **código 👩‍💻:**
    - En el jupyter de preliminary no se te renderiza la imagen por la ruta:

        ```python
        "![texto_descriptivo](portada.jpg)"
        ```

        está dentro de la carpeta de imágenes, por lo que se lo tienes que decir. 

    - Las docstrings están muy top.
    - En la función de get_age:

        ```python
        try:
                return re.findall(pattern, x), age [0]
            except:
                pass
        ```

        puedes hacer que te devuelva "np.nan", que es un objeto de python con el que puedes trabajar.

        Lo mismo con la función de searching.  Puedes hacer que en vez de que te devuelva la string, te devuelva un Nan.

    - Para la función de clean_fatal:

        ```python
        if x == "y":
                return "Y"
            elif x == "Y":
                return "Y"
            elif x == " N" or x == "N":
                return "N"
            elif x == "M" or x == "2017":
                return "UNKNOWN"
            else:
                return "UNKNOWN"
        ```

        esto lo puedes refactorizar por dos frentes: los espacios y las mayúsculas. ¿se te ocurre cómo?

    - Para la función de guardar gráficos: como estás dentro de tu propio proyecto y conoces la ruta donde se van a guardar siempre (o bien la carpeta de data o bien la de output) puedes ahorrarte el path. O bueno, al menos la parte principal. Sólo te haría falta el nombre que le quieras dar al archivo (igual lo has hecho así en los jupyters.  Ahora voy a ello! )
    - Para el renaming de las columnas:

        ```python
        df.rename(columns = {'Sex ':'Sex'}, inplace = True)
        ```

        igual te resulta más cómodo utilizar métodos de python como .strip() o .lower()

    - Cuando hablamos del scroll infinito, nos refereimos a esto: [https://github.com/Unaiat/Shark_Attack_Project/blob/main/Data_cleaning.ipynb](https://github.com/Unaiat/Shark_Attack_Project/blob/main/Data_cleaning.ipynb). Limita el output o "clear it", para que quien entre a verlo pueda encontrar tu código.
    - Las funciones que ya hayas importado desde el archivo de limpieza/visualización, no hace falta que las tengas de nuevo definidas en el jupyter, bórralas!
    - Te diría también que puedes hacer la limpieza en todas las columnas y luego exportar un sólo csv. Entiendo que exportes varios por si acaso, pero no hace falta que tengas uno por hipótesis.
    - Los gráficos están bien: son sencillos y muestran lo que tienen que mostrar. Son fácilmente interpretables.
    - El story-telling lo veo genial también.

    Buen trabajo Unai 😃💪 Está muy bien el proyecto; sólo esos detalles que te comento.

    A por pipelineeeees! 

    ![https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png](https://user-images.githubusercontent.com/54676992/106113904-4271d880-614f-11eb-9326-6a06e40aaf3e.png)
